### ISSUE TITLE
Header logo fails branding guidelines

### ISSUE THREAD

**Issue by marcsoler** [flybywiresim/website#111]
Source: https://raw.githubusercontent.com/flybywiresim/fbw-branding/master/jpg/FBW-Branding-Guidelines.jpg

Current (fails rule 1):
![image](https://user-images.githubusercontent.com/1502124/108512203-27fbcc80-72c1-11eb-8d2e-471d7a4e5630.png)

Issue caused with oficial logo (fails rule 3):
![image](https://user-images.githubusercontent.com/1502124/108512297-49f54f00-72c1-11eb-9c7b-5818a757ff39.png)

Suggestion would be using a dark header with the current sub-navigation color:
![image](https://user-images.githubusercontent.com/1502124/108512026-f256e380-72c0-11eb-80f1-458b63a4bf84.png)

**Comment by NathanInnes** [comment]
Your issue is more appropriate on this repository https://github.com/flybywiresim/docs

I will forward it for you if you'd like.

**Comment by marcsoler** [comment]
> Your issue is more appropriate on this repository https://github.com/flybywiresim/docs
> 
> I will forward it for you if you'd like.

Oh right! I would appreciate that. Thank you

**Comment by marcsoler** [comment]
> Your issue is more appropriate on this repository https://github.com/flybywiresim/docs

Acutally this also applies for the website itself (rule 1 of the guideline):
![image](https://user-images.githubusercontent.com/1502124/108524860-ca22b100-72cf-11eb-8b93-b2a59575c679.png)

**Comment by NathanInnes** [comment]
Rule number 1 applies to external sources who modify the logo, the one used here is in the repository and states up top of the branding guidelines to use the ones we provide

**Comment by NathanInnes** [comment]
I made a PR on the docs branch fixing the background, all should be resolved now.

**Comment by Valastiri** [comment]
Thanks for bringing up the docs logo. Should be fixed.

**Comment by NathanInnes** [comment]
Going to close this issue now as it's resolved.
