### ISSUE TITLE
Menu bar peaking in video

### ISSUE THREAD

**Issue by armankir** [flybywiresim/website#117]
Menu bar peaks out on desktop and mobile

![image](https://user-images.githubusercontent.com/70278701/108606037-ade14b80-7385-11eb-8a1d-4b671fd8106c.png)

![unknown](https://user-images.githubusercontent.com/70278701/108606067-df5a1700-7385-11eb-9dc8-453e13ccc01e.png)

**Comment by NathanInnes** [comment]
@yorgosGK could you crop the top part to remove the msfs menu?

**Comment by NathanInnes** [comment]
Very minor detail, not worth going through to fix

**Comment by yorgosGK** [comment]
Oh wow. Just saw this now. I still can if mandatory. I was told its cropped
by sabes.
