### ISSUE TITLE
[CHANGE] Transition to @tabler/icons

### ISSUE THREAD

**Issue by NathanInnes** [flybywiresim/website#157]
## Suggested feature/change
Convert all current icons to our own forked tabler icons https://github.com/flybywiresim/tabler-icons 

## Explain the feature/change(if applicable)

+ Good range of icons
+ No paywall for good icons
+ More flexible

*Disclaimer if the feature/change is due to personal preference it may be subject to a discussion.*

**Comment by GhostEagle68** [comment]
I'll look into this later today and provide some screen shots in discord 👍

**Comment by ErickSharp** [comment]
Are we using our own fork or the new release of tabler-icons? The latest release came out 4 days ago.

**Comment by NathanInnes** [comment]
Should be good now to use the official version instead of our fork

**Comment by ErickSharp** [comment]
We will probably get this done when we get the projects page redesign set up.

**Comment by NathanInnes** [comment]
Closing issue as better icon pack has been found.
