### ISSUE TITLE
[FEATURE/CHANGE] INSERT TITLE HERE: weather radar

### ISSUE THREAD

**Issue by zww55** [flybywiresim/website#434]
## Suggested feature/change
< Make a brief remark about the feature/change you wish to see >

## Explain the feature/change(if applicable)
< Explain to the best of your ability the feature/change so people can understand what to do. >

*Disclaimer if the feature/change is due to personal preference it may be subject to a discussion.*

**Comment by zww55** [comment]
Waiting for a very long time, what's the problem? Thank you.

**Comment by frankkopp** [comment]
This is not a web site related issue. Also see our NOTAM for this topic and direct your question to Asobo :)
